# Generated by Django 4.2.25 on 2025-10-19 18:20

from django.db import migrations
from django.conf import settings

def set_default_owner(apps, schema_editor):
    # Modelle dynamisch über apps holen (WICHTIG in Data Migrations!)
    Quiz = apps.get_model('quiz_app', 'Quiz')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    # Wähle einen Default-Owner: bevorzugt Superuser, sonst irgendein User
    owner = User.objects.filter(is_superuser=True).first() or User.objects.first()
    if owner:
        Quiz.objects.filter(owner__isnull=True).update(owner=owner)
    # Falls es gar keinen User gibt, lass owner NULL – und ändere später nicht auf null=False.

class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quiz_owner'),
    ]

    operations = [
        migrations.RunPython(set_default_owner, migrations.RunPython.noop),
    ]
