# Generated by Django 4.2.25 on 2025-10-19 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0003_backfill_quiz_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(default=True, help_text='Ersteller des Quizzes', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
